const SIDEBAR_WIDTH = 400;
const MAPBOX_ACCESS_TOKEN = "pk.eyJ1IjoiamVmZnJleWNhbzE5OTgiLCJhIjoiY2tqenR5NmM1MDhwNDJ2cGU4OGdjaWw3aCJ9.SYRSBCyFZV7UclciOm5g-Q";

export {
  MAPBOX_ACCESS_TOKEN,
  SIDEBAR_WIDTH,
}